name: Deploy

on:
  push:
    branches: [ master, release ]

jobs:
  build_and_deploy:
    name: Build app and lambdas
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: ./ci.sh install

    - name: Build lambdas
      run: |
        ./ci.sh build scraper
        ./ci.sh build contact
        ./ci.sh build image

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -input=false && terraform refresh -input=false

    - name: Select Terraform Workspace
      if: github.ref != 'refs/heads/release'
      run: terraform workspace select staging

    - name: Terraform Validate
      run: terraform apply -auto-approve -input=false
      env:
        TF_VAR_mailgun_api_key: ${{ secrets.MAILGUN_API_KEY }}
        TF_VAR_pjsc_key: ${{ secrets.PJSC_KEY }}

    - name: Build App
      run: ./build-app.sh

    - name: Deploy App
      run: ./deploy-app.sh
