name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Validate IAC and Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Create placeholder files
      run: |
        mkdir -p contact/build image/build scraper/build
        touch contact/build/contact.zip image/build/image.zip scraper/build/scraper.zip

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Terraform Init
      run: |
        terraform init -input=false && terraform refresh -input=false
        terraform workspace select staging

    - name: Validate Terraform IAC
      run: terraform plan -input=false

    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: ./ci.sh ci-install

    - name: Run unit tests
      run: ./ci.sh test

    - name: Build and serve app
      run: ./ci.sh build app

    - name: Run e2e tests
      run: |
        ./ci.sh run --prod &
        ./ci.sh cypress
      env:
        CYPRESS_BASE_URL: http://localhost:5000
