name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Validate IAC and Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Validate Terraform IAC
      run: |
        ./tf.sh init
        ./tf.sh validate

    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: ./ci.sh ci-install

    - name: Lint Code
      run: ./ci.sh lint

    - name: Run unit tests
      run: ./ci.sh test
