# GitHub Actions workflow

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Unit and E2E Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: ./ci.sh ci-install

    - name: Run tests
      run: ./ci-test.sh

  terraform:
    name: Verify IAC
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -input=false

    - name: Create placeholder files
      run: |
        mkdir -p contact/build image/build scraper/build
        touch contact/build/contact.zip image/build/image.zip scraper/build/scraper.zip

    - name: Terraform Validate
      run: terraform plan -input=false
