name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: ./ci.sh ci-install

    - name: Lint code
      run: ./ci.sh lint

    - name: Run unit tests
      run: ./ci.sh test

    - name: Deploy IAC (terraform)
      run: |
        ./deploy/tf.sh init
        ./deploy/tf.sh validate
