name: CI

on:
  pull_request:
    branches: [ master, release ]

jobs:
  test:
    name: Validate IAC and Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Create placeholder files
      run: |
        mkdir -p contact/build image/build scraper/build
        touch contact/build/contact.zip image/build/image.zip scraper/build/scraper.zip

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Validate Terraform IAC
      run: |
        ./tf.sh init
        ./tf.sh workspace select staging
        ./tf.sh plan -refresh=false
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

    - name: Setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      run: ./ci.sh ci-install

    - name: Run unit tests
      run: ./ci.sh test

    - name: Build app
      run: ./ci.sh build app unsw

    - name: Run e2e tests
      if: github.ref == 'refs/heads/release'
      run: ./ci.sh cypress run
      env:
        CYPRESS_BASE_URL: staging.crossangles.com
